plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version + '+' + project.minecraft_version

repositories {
}

base {
	archivesName = project.archives_base_name
}

loom {
	accessWidenerPath = file("src/main/resources/amber.accesswidener")
}

dependencies {
	minecraft("com.mojang:minecraft:${project.minecraft_version}")
	implementation("net.fabricmc:fabric-loader:${project.loader_version}")

	implementation(fabricApi.module("fabric-resource-loader-v0", project.fabric_api_version))
}

processResources {
	def version = project.version
	inputs.property("version", version)

	filesMatching("fabric.mod.json") {
		expand("version": project.version, "fabricloader": project.loader_version, "minecraft": project.minecraft_range)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property("projectName", projectName)

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}